# Generated by Django 2.0.7 on 2020-09-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gp',
            name='Numbers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gp',
            name='Punctuation',
            field=models.BooleanField(default=False),
        ),
    ]
