# Generated by Django 2.0.7 on 2020-09-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Password', '0002_auto_20200902_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gp',
            name='Numbers',
        ),
        migrations.RemoveField(
            model_name='gp',
            name='Punctuation',
        ),
    ]
